### ISSUE TITLE
download the top 100 paper from the text mining results

### ISSUE THREAD

**Issue by elipapa** [opentargets/platform_issues_triage#14]
these should be ranked by some measure of significance. EuropePMC does provide an internal score we could use.

**Comment by deniseOme** [comment]
The user would appreciate it if we could  add back the download button. They've suggested to add a maximum number exported to make it less technically challenging. They are not sure what that number would be.

**Comment by deniseOme** [comment]
Latest communication with the user, the REST API endpoint (https://targetvalidation.org/api/latest/public/evidence/filter?target=ENSG00000182578&disease=EFO_0000249&datatype=literature&format=tab) was provided as an alternative for the time being.

**Comment by deniseOme** [comment]
The original user request was: "is there a way for me to pull the articles from your Europe PMC Text mining for a particular gene/target combination? For example via a static web link or the open targets API".

**Comment by elipapa** [comment]
Issue moved to [opentargets/webapp #118](https://github.com/opentargets/webapp/issues/118) via [**ZenHub**](https://www.zenhub.com/)
