### ISSUE TITLE
Is there a way to automatically download the gtex image? And the expression atlas image? 

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues_triage#15]
I had discussed this with @emepyc offline.
I got back to the user with the possibility that we will try to write a script to allow for the expression data for a given gene to be retrieved and the png file to be generated.

As soon we have a first version of this script, we will follow this up with the user.

**Comment by elipapa** [comment]
the image can be downloaded, one-by-one. 
to do it programmatically seems an edge case. 
we don't host the data and GTEX has a way of download the image anyways.
