### ISSUE TITLE
link to opentargets/github

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues_triage#18]
One user at a workshop suggested having a link to our github.

Perhaps from the API menu?!?!?

![screen shot 2017-03-08 at 17 22 28](https://cloud.githubusercontent.com/assets/6472381/23715236/d7982870-0423-11e7-877d-f3f54a7efec3.png)

**Comment by nikiforosk** [comment]
Maybe this Menu should be called "For developers" (and perhaps include the Downloads)?

See e.g. the ubuntu site: 
https://developer.ubuntu.com/en/?_ga=1.221482712.1161247147.1489052972

**Comment by deniseOme** [comment]
We may revisit this later...Perhaps get some use cases, and the advantages of having the link (just to say we are open? We want to expose our codebase? If the latter, there may be other ways to do so.

**Comment by elipapa** [comment]
we'll include it in the footer.

**Comment by elipapa** [comment]
Issue moved to [opentargets/webapp #117](https://github.com/opentargets/webapp/issues/117) via [**ZenHub**](https://www.zenhub.com/)
