### ISSUE TITLE
R client: can we maintain it?

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues_triage#19]
At the omics integration course (March 2017 at EMBL-EBI), at least two attendees wish the R client to be maintained by Open Targets.

**Comment by deniseOme** [comment]
we created the same issue twice almost at the same time, @ckongEBI

**Comment by elipapa** [comment]
the final decision is: best effort support, but not official support...
@deniseOme we should probably write this in the REPO of the rclient
