### ISSUE TITLE
your target list tool: pasting 

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues_triage#22]
This has been discussed with @emepyc on slack.

At the omic integration course (March 2017, EMBL-EBI) one user suggested having a box for entering the data (in addition to the upload file options) e.g.

![](https://files.slack.com/files-pri/T02UV853T-F4FAJ1E58/screen_shot_2017-03-08_at_11.56.47.png)

This may no longer be needed when the batch search is up and running.
Batch search will allow pasting the list. @emepyc's started implementing this but found  inconsistencies with our current flow (upload list vs manually add more targets vs copy paste a list). The search will evolve based on user feedback).

**Comment by elipapa** [comment]
batch search takes care of that
