### ISSUE TITLE
Clinical phases trials: FAQ

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues_triage#24]
When we teach workshops to a wider audience (not only DDU), there can be questions such as what does phase 0, 1, 2, 3, 4 mean. We need a FAQ (with or without a cartoon)

https://www.cancerresearchuk.org/about-cancer/find-a-clinical-trial/what-clinical-trials-are/phases-of-clinical-trials

https://www.nlm.nih.gov/services/ctphases.html

**Comment by elipapa** [comment]
faq now pointing to https://www.fda.gov/downloads/Drugs/ResourcesForYou/Consumers/UCM284393.pdf

@emepyc should we embed this one?
