### ISSUE TITLE
I'd like to search genomic coordinates

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues_triage#27]
This request has last been made by Nizar Smaoui at Platform training session for Takeda. It's been requested by other workshops' attendees as well.

Related to #26. 

Once the FAQ on genome assembly is out, it will be clearer to users that we try to be as assembly agnostic as possible.

I don't know which results they expect from a search using coordinates. I can ask next time round.

If (and it's a big if) we were to implement this, we could return genes and diseases akin to watch the drug matches return. We would give a limit on the chunk to query.

**Comment by elipapa** [comment]
better suited to a genome browser.

**Comment by deniseOme** [comment]
whenever a user asks this, point them to Ensembl.

**Comment by elipapa** [comment]
@deniseOme should we include this decision in the FAQ?
