### ISSUE TITLE
show the gene expression and exon expression plots from GTEx on the open targets target profile page

### ISSUE THREAD

**Issue by elipapa** [opentargets/platform_issues_triage#7]
It'd be helpful to show the gene expression and exon expression plots from GTEx (images below) on the open targets target profile page. I also like how the default GTEx grouping is by body region (e.g. brain)

**Comment by deniseOme** [comment]
Done for the December 2016 release!

**Comment by deniseOme** [comment]
Close #7

**Comment by emepyc** [comment]
We don't have plots for the exon expression (or isoforms), but I think we decided that we won't be replicating all the GTEx plots in OT (we already offer a link out).
I think one of the use cases for that is that the user was able to export our images and that was not possible in the GTEx portal (just for the record)

**Comment by deniseOme** [comment]
Yes, you are right. My bad.

**Comment by deniseOme** [comment]
I did not know we had decided we won't be replicating all the GTEx plots in OT (we already offer a link out). I will let Paola know. I can also ask her why would she like that from OT rather than the original source (perhaps she will mention the added value we provide for the image export).

**Comment by emepyc** [comment]
Ah, ok, yes, you missed that meeting. This was discussed on the weekly meeting you were in the US. We decided that we shouldn't replicate all the options they have.
And yes, I think you mentioned that (at least one of the reasons) she wanted us to replicate the plot because she was able to download our images :-/

**Comment by deniseOme** [comment]
So we should close this?

**Comment by deniseOme** [comment]
email sent to Paola.
